---
apiVersion: v1
kind: Pod
metadata:
  name: ldap-client
spec:
  containers:
    - name: ldap-client
      image: particlekit/ldap-client
      command:
        - tail
        - -f
        - /dev/null
